### ISSUE TITLE
Error importing module during EM add-on activation

### ISSUE THREAD

**Issue by livmion** [zalmoxes-laran/EM-blender-tools#5]
Dear Emanuel,

if I try to enable EM on Blender (version 2.93 or 3.0), the following error appears:

`Modules Installed (EM-blender-tools-v.1.2.0) from '/home/livmion/Downloads/Pacchetti/Blender/EM-blender-tools-v.1.2.0.zip' into '/home/livmion/.var/app/org.blender.Blender/config/blender/3.0/scripts/addons'
Traceback (most recent call last):
  File "/app/blender/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'EM-blender-tools-v'
`

The same problem affects the last version and also older versions, as well 3DSC.
I am currently running Blender on Debian Bullseye.

Thank you very much in advance

**Comment by zalmoxes-laran** [comment]
Dear livmion,
unfortunately is a matter of how Blender reads the name of the addons as they are written by github. Nothing we can change. The work-around way is a very simple 3 steps move:
1- download the EM-blender-tools-v.1.2.0.zip
2- open it with a zip software like 7zip or unpack it to see the contained folder "EM-blender-tools-v.1.2.0"
3- rename it from "EM-blender-tools-v.1.2.0" to "EM-blender-tools" and zip back it to EM-blender-tools.zip

now you can install it. if you are in mac os, do not use the os zipper but use keka instead (mac add some pity files that broke the addon). Same thing with 3DSC
